#!/bin/bash

# Prompt user for password
read -sp "Enter your password: " password
echo

# Check strength
if [[ ${#password} -ge 8 && "$password" =~ [A-Za-z] && "$password" =~ [0-9] ]]; then
    echo "strong password"
elif [[ ${#password} -ge 6 && ${#password} -lt 8 && "$password" =~ [A-Za-z] ]]; then
    echo "moderate password"
else
    echo "weak password"
fi

